
services:
  api:
    container_name: css-api
    build:
      context: .
    environment:
      NODE_ENV: production
    depends_on: 
      - mongo
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules
      
  mongo:
    container_name: mongodb-database
    image: mongo:latest
    volumes:
      - mongodb:/data/db

  mongo-express:
    container_name: mongo-express-ui
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

volumes:
  mongodb:

